# Generated by Django 3.2.5 on 2022-03-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('ruc', models.CharField(blank=True, max_length=100, null=True)),
                ('vendedor', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('dirreccion', models.CharField(max_length=100, null=True)),
                ('formaPago', models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Credito')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('status', models.BooleanField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.categoria')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.marca')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numFac', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('moneda', models.CharField(choices=[('CORDOBAS', 'CORDOBAS'), ('DOLARES', 'DOLARES')], max_length=100, null=True)),
                ('iva', models.FloatField()),
                ('subTotal', models.FloatField()),
                ('total', models.FloatField()),
                ('tipoCambio', models.FloatField()),
                ('formaPago', models.CharField(choices=[('TRANSFERENCIA', 'TRANSFERENCIA'), ('CHEQUE', 'CHEQUE'), ('EFECTIVO', 'EFECTIVO'), ('TARJETA', 'TARJETA')], max_length=100, null=True)),
                ('detalle', models.CharField(max_length=100, null=True)),
                ('cantidad', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('fecha', models.DateField()),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.proveedor')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Factura',
            },
        ),
    ]