# Generated by Django 3.2.5 on 2023-04-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_factura_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
