# Generated by Django 3.2.5 on 2023-05-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_alter_detallefactura_numfac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='formaPago',
            field=models.CharField(choices=[('Transferencia', 'Transferencia'), ('Cheque', 'Cheque'), ('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='moneda',
            field=models.CharField(choices=[('Córdobas', 'Córdobas'), ('Dólares', 'Dólares')], max_length=100, null=True),
        ),
    ]
