# Generated by Django 3.2.5 on 2022-03-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('area', models.CharField(choices=[('CONTABILIDAD', 'CONTABILIDAD'), ('OPERACIONES', 'OPERACIONES'), ('SERVICIO AL CLIENTE', 'SERVICIO AL CLIENTE'), ('ADMINISTRACION', 'ADMINISTRACION')], max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'producto',
            },
        ),
    ]
