# Generated by Django 3.2.5 on 2023-05-11 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='km_fin',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='km_inicio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='litros',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='consumo',
            name='monto',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='vehiculo',
            field=models.CharField(choices=[('Motocicleta', 'Motocicleta'), ('Microbús', 'Microbús'), ('Camioneta', 'Camioneta'), ('Carro', 'Carro')], max_length=100, null=True),
        ),
    ]
